### ISSUE TITLE
Too many "Sorry, I do not understand you"

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/waiter#4]
I think there are too many "Sorry, I do not understand you", which end up _disconforting_ people that interact or watch how we interact with Teo.

Possible solutions that come to my mind are:
- Add a counter of maximum "Sorry, I do not understand you" per unit of time (i.e. saying it only one each minute).
- Add different alternative sentences to add diversity to the possible answers.
- Combine both.

**Comment by jgvictores** [comment]
The number of failed ASR incremented with https://github.com/roboticslab-uc3m/teo-head/commit/d3e94034a09aa23991f1d7f94548ead7fd3fbce8, which was an attempt at effortlessly solving https://github.com/roboticslab-uc3m/teo-head/issues/32 (for roboticslab-uc3m/waiter).
This should be improved on both ends.

**Comment by rsantos88** [comment]
To avoid problems with voice recognition by microphone, I've added a module in the xml (https://github.com/roboticslab-uc3m/waiter/commit/a85d287caec08dc657ee019e512ee74343b16d40) to send the voice commands, directly by keyboard without the need to use a microphone. Can I close this issue?

**Comment by jmgarciah** [comment]
for me, it's ok.

**Comment by rsantos88** [comment]
Thanks!
