### ISSUE TITLE
Make this demo work

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/waiter#7]
Después de los diversos cambios realizados en los repositorios, cambio de versión de yarp, etc... esta demo se ha dejado un poco de lado. Abro esta issue para hacerla funcional, tal y como estaba antes.

**Comment by rsantos88** [comment]
Actualmente esta demo está totalmente fuera de uso debido a que:
* Se necesita que esté funcional la pinza de la mano derecha (ahora está desconectada y la PCB de la mano baila continuamente porque no tiene nada más que un tornillo que la sujeta...)
* Debido al cambio del antebrazo izquierdo, el axial de la mano derecha no gira, por lo que no puede realizar movimientos con la bandeja.

A tener en cuenta que además, habría que revisar de nuevo las posiciones grabadas de los brazos al realizar el grasping de la botella, ya que ahora las longitudes de los brazos son ligeramente diferentes debido al cambio de los antebrazos.

**Comment by jgvictores** [comment]
¿ Quizás se debería mencionar algo en http://robots.uc3m.es/index.php/Procedimiento_Demos ?

**Comment by rsantos88** [comment]
¿Algo así? :

== ̶D̶e̶m̶o̶ ̶w̶a̶i̶t̶e̶r̶ == (NO FUNCIONAL)
Inicializar

    Doble-click en icono escritorio "waiter yarpmanager"
    Click en triángulo de la izquierda de "Application".
    Doble-click en "waiter_english_App".
    Click en "Run" (botón verde con forma Play).
    Click en "Connect" (botón verde a derecha de "Run").
    Comandos de voz:
        hi teo.
            give me water.
            thank you.
        stop teo.

Cerrar

    Click en "Disconnect" (botón rojo a derecha de "Connect").
    Click en "Stop" (botón rojo a derecha de "Disconnect").
    Si hay problemas, existe un botón "Kill" (botón calavera a derecha de "Stop"), que a veces ayuda.

**Comment by jgvictores** [comment]
Sí, sería genial!

**Comment by rsantos88** [comment]
Listo!

**Comment by jgvictores** [comment]
Perfecto, Gracias!

**Comment by rsantos88** [comment]
Actualizada la demo "waiter" integrando las nuevas interfaces `IControlMode2`, `IPositionControl2` e `IVelocityControl2` y eliminando funciones obsoletas (f92f997f5866755d8f5365433b96239757d6424f)

ToDo:
* Probarla en el robot.
* Grabar las trayectorias del brazo nuevamente en caso que sea necesario, debido al cambio de longitud del antebrazo.

**Comment by rsantos88** [comment]
Grabadas nuevas posiciones del brazo derecho e izquierdo (https://github.com/roboticslab-uc3m/waiter/commit/d17be7651861c71fd6125350765d86ee5f7ed6e3), adaptadas a las nuevas posiciones de las muñecas (ver [issue](https://github.com/roboticslab-uc3m/teo-bimanipulation/issues/2#issuecomment-388315059) relacionada).
ToDo:
 * Probar los nuevos cambios en el robot
 * Corregir fallos que surjan

**Comment by rsantos88** [comment]
A la espera de https://github.com/roboticslab-uc3m/teo-hardware-issues/issues/29

**Comment by rsantos88** [comment]
Últimos cambios: https://github.com/roboticslab-uc3m/waiter/pull/8
La demo ahora es totalmente operativa. Cierro esta issue
