### ISSUE TITLE
Update joint-space commands

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/waiter#9]
Update joint-space commands, changed at https://github.com/roboticslab-uc3m/teo-main/issues/39

**Comment by rsantos88** [comment]
Pending to merge this https://github.com/roboticslab-uc3m/waiter/pull/8 before

**Comment by rsantos88** [comment]
Done here: https://github.com/roboticslab-uc3m/waiter/pull/10. Pending to test on Teo

**Comment by rsantos88** [comment]
@jmgarciah, correct me if you disagree. This issue was finished, at least the joint direction of rotation due to a video that we recorded for your thesis. So I'll do a merge of this branch and close this issue.
